<SVGTSpanElementg>
    dfsgsed
    sdfgde
    sdfgd
    asdg
    asgs
    sadfgsadrf
    dgsdrfserg
    gvsretfgswrt
    rtfgwsertgwsertfg
    rtgwsergwsrtgwretg
    rtgwsertgertgrsetghrtgqrfe3ergwaerfgwe
    aerfg
    wsergw
    erg
    wergwsergwerg
</SVGTSpanElementg>